name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distributrion: 'adopt'
        java-version: '11'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
     
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4    
    - uses: actions/setup-java@v3
      with:
        distributrion: 'adopt'
        java-version: '11'
        node-version: '20x'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.war staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
